// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-fa0ZF2dq1btLFbJlTjhQBN4Tk9hG0U0',
    appId: '1:238663203816:web:85322705aeffbf5399c25d',
    messagingSenderId: '238663203816',
    projectId: 'hebatani-fe74a',
    authDomain: 'hebatani-fe74a.firebaseapp.com',
    storageBucket: 'hebatani-fe74a.appspot.com',
    measurementId: 'G-L71K69LES4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWSCX2krCHWwMbhFlhdHJ_OaiBUfk1OpA',
    appId: '1:238663203816:android:c48446d9cce6bb6399c25d',
    messagingSenderId: '238663203816',
    projectId: 'hebatani-fe74a',
    storageBucket: 'hebatani-fe74a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDt4mEb5ekpfsOjHjWXn5LDyGCOWH2Noeg',
    appId: '1:238663203816:ios:146d1c2fc8bd4cc299c25d',
    messagingSenderId: '238663203816',
    projectId: 'hebatani-fe74a',
    storageBucket: 'hebatani-fe74a.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDt4mEb5ekpfsOjHjWXn5LDyGCOWH2Noeg',
    appId: '1:238663203816:ios:146d1c2fc8bd4cc299c25d',
    messagingSenderId: '238663203816',
    projectId: 'hebatani-fe74a',
    storageBucket: 'hebatani-fe74a.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-fa0ZF2dq1btLFbJlTjhQBN4Tk9hG0U0',
    appId: '1:238663203816:web:3d595c24e3c2b92999c25d',
    messagingSenderId: '238663203816',
    projectId: 'hebatani-fe74a',
    authDomain: 'hebatani-fe74a.firebaseapp.com',
    storageBucket: 'hebatani-fe74a.appspot.com',
    measurementId: 'G-0QHLTBKB8E',
  );
}
